//
// Copyright (c) 2024, Dylam De La Torre <dyxel04@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: duel_data.proto

// TODO: Documentation.

package ygopenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainStatus int32

const (
	// NOTE: CHAINING is never actually sent, but it's the default status when
	// a Chain is pushed on top of the ChainStack.
	ChainStatus_CHAIN_STATUS_CHAINING    ChainStatus = 0
	ChainStatus_CHAIN_STATUS_CHAINED     ChainStatus = 1
	ChainStatus_CHAIN_STATUS_SOLVING     ChainStatus = 2
	ChainStatus_CHAIN_STATUS_ACT_NEGATED ChainStatus = 3 // Activation negated.
	ChainStatus_CHAIN_STATUS_EFF_NEGATED ChainStatus = 4 // Effect negated.
)

// Enum value maps for ChainStatus.
var (
	ChainStatus_name = map[int32]string{
		0: "CHAIN_STATUS_CHAINING",
		1: "CHAIN_STATUS_CHAINED",
		2: "CHAIN_STATUS_SOLVING",
		3: "CHAIN_STATUS_ACT_NEGATED",
		4: "CHAIN_STATUS_EFF_NEGATED",
	}
	ChainStatus_value = map[string]int32{
		"CHAIN_STATUS_CHAINING":    0,
		"CHAIN_STATUS_CHAINED":     1,
		"CHAIN_STATUS_SOLVING":     2,
		"CHAIN_STATUS_ACT_NEGATED": 3,
		"CHAIN_STATUS_EFF_NEGATED": 4,
	}
)

func (x ChainStatus) Enum() *ChainStatus {
	p := new(ChainStatus)
	*p = x
	return p
}

func (x ChainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_duel_data_proto_enumTypes[0].Descriptor()
}

func (ChainStatus) Type() protoreflect.EnumType {
	return &file_duel_data_proto_enumTypes[0]
}

func (x ChainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainStatus.Descriptor instead.
func (ChainStatus) EnumDescriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{0}
}

type FieldShape struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use 3 Monster and Spell&Trap Zones instead of the usual 5.
	ThreeColumns bool `protobuf:"varint,1,opt,name=three_columns,json=threeColumns,proto3" json:"three_columns,omitempty"`
	// Use Pendulum Zones (Treat cornering Spell&Trap Zones as both).
	HasPzones bool `protobuf:"varint,2,opt,name=has_pzones,json=hasPzones,proto3" json:"has_pzones,omitempty"`
	// Separate the Pendulum Zones from cornering Spell&Trap Zones.
	HasSeparatePzones bool `protobuf:"varint,3,opt,name=has_separate_pzones,json=hasSeparatePzones,proto3" json:"has_separate_pzones,omitempty"`
	// Use Extra Monster Zones.
	HasEmzones bool `protobuf:"varint,4,opt,name=has_emzones,json=hasEmzones,proto3" json:"has_emzones,omitempty"`
	// Use Skill Zone (for specific Skills that use it).
	HasSkillZone  bool `protobuf:"varint,5,opt,name=has_skill_zone,json=hasSkillZone,proto3" json:"has_skill_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldShape) Reset() {
	*x = FieldShape{}
	mi := &file_duel_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldShape) ProtoMessage() {}

func (x *FieldShape) ProtoReflect() protoreflect.Message {
	mi := &file_duel_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldShape.ProtoReflect.Descriptor instead.
func (*FieldShape) Descriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{0}
}

func (x *FieldShape) GetThreeColumns() bool {
	if x != nil {
		return x.ThreeColumns
	}
	return false
}

func (x *FieldShape) GetHasPzones() bool {
	if x != nil {
		return x.HasPzones
	}
	return false
}

func (x *FieldShape) GetHasSeparatePzones() bool {
	if x != nil {
		return x.HasSeparatePzones
	}
	return false
}

func (x *FieldShape) GetHasEmzones() bool {
	if x != nil {
		return x.HasEmzones
	}
	return false
}

func (x *FieldShape) GetHasSkillZone() bool {
	if x != nil {
		return x.HasSkillZone
	}
	return false
}

type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NOTE: Must be 4 values (256 bits).
	Seed []uint64 `protobuf:"varint,1,rep,packed,name=seed,proto3" json:"seed,omitempty"`
	// NOTE: Must be at least one for each team.
	DuelistsFirst  []*Options_Duelist `protobuf:"bytes,2,rep,name=duelists_first,json=duelistsFirst,proto3" json:"duelists_first,omitempty"`
	DuelistsSecond []*Options_Duelist `protobuf:"bytes,3,rep,name=duelists_second,json=duelistsSecond,proto3" json:"duelists_second,omitempty"`
	Shape          *FieldShape        `protobuf:"bytes,4,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_duel_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_duel_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetSeed() []uint64 {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *Options) GetDuelistsFirst() []*Options_Duelist {
	if x != nil {
		return x.DuelistsFirst
	}
	return nil
}

func (x *Options) GetDuelistsSecond() []*Options_Duelist {
	if x != nil {
		return x.DuelistsSecond
	}
	return nil
}

func (x *Options) GetShape() *FieldShape {
	if x != nil {
		return x.Shape
	}
	return nil
}

type Chain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardPlace     *Place                 `protobuf:"bytes,1,opt,name=card_place,json=cardPlace,proto3" json:"card_place,omitempty"`
	Place         *Place                 `protobuf:"bytes,2,opt,name=place,proto3" json:"place,omitempty"`
	Effect        *Effect                `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_duel_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_duel_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{2}
}

func (x *Chain) GetCardPlace() *Place {
	if x != nil {
		return x.CardPlace
	}
	return nil
}

func (x *Chain) GetPlace() *Place {
	if x != nil {
		return x.Place
	}
	return nil
}

func (x *Chain) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_duel_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_duel_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{3}
}

func (x *Counter) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Counter) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Effect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_duel_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_duel_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{4}
}

func (x *Effect) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Effect) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Con           int32                  `protobuf:"varint,1,opt,name=con,proto3" json:"con,omitempty"`     // Controller.
	Loc           uint32                 `protobuf:"varint,2,opt,name=loc,proto3" json:"loc,omitempty"`     // Location.
	Seq           uint32                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`     // Sequence.
	Oseq          int32                  `protobuf:"zigzag32,4,opt,name=oseq,proto3" json:"oseq,omitempty"` // Overlay sequence, < 0 for invalid sequence.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_duel_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_duel_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{5}
}

func (x *Place) GetCon() int32 {
	if x != nil {
		return x.Con
	}
	return 0
}

func (x *Place) GetLoc() uint32 {
	if x != nil {
		return x.Loc
	}
	return 0
}

func (x *Place) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Place) GetOseq() int32 {
	if x != nil {
		return x.Oseq
	}
	return 0
}

type Options_Duelist struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartingLp        uint32                 `protobuf:"varint,1,opt,name=starting_lp,json=startingLp,proto3" json:"starting_lp,omitempty"`
	StartingDrawCount uint32                 `protobuf:"varint,2,opt,name=starting_draw_count,json=startingDrawCount,proto3" json:"starting_draw_count,omitempty"`
	DrawCountPerTurn  uint32                 `protobuf:"varint,3,opt,name=draw_count_per_turn,json=drawCountPerTurn,proto3" json:"draw_count_per_turn,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Options_Duelist) Reset() {
	*x = Options_Duelist{}
	mi := &file_duel_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Duelist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Duelist) ProtoMessage() {}

func (x *Options_Duelist) ProtoReflect() protoreflect.Message {
	mi := &file_duel_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Duelist.ProtoReflect.Descriptor instead.
func (*Options_Duelist) Descriptor() ([]byte, []int) {
	return file_duel_data_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Options_Duelist) GetStartingLp() uint32 {
	if x != nil {
		return x.StartingLp
	}
	return 0
}

func (x *Options_Duelist) GetStartingDrawCount() uint32 {
	if x != nil {
		return x.StartingDrawCount
	}
	return 0
}

func (x *Options_Duelist) GetDrawCountPerTurn() uint32 {
	if x != nil {
		return x.DrawCountPerTurn
	}
	return 0
}

var File_duel_data_proto protoreflect.FileDescriptor

const file_duel_data_proto_rawDesc = "" +
	"\n" +
	"\x0fduel_data.proto\x12\x11YGOpen.Proto.Duel\"\xc7\x01\n" +
	"\n" +
	"FieldShape\x12#\n" +
	"\rthree_columns\x18\x01 \x01(\bR\fthreeColumns\x12\x1d\n" +
	"\n" +
	"has_pzones\x18\x02 \x01(\bR\thasPzones\x12.\n" +
	"\x13has_separate_pzones\x18\x03 \x01(\bR\x11hasSeparatePzones\x12\x1f\n" +
	"\vhas_emzones\x18\x04 \x01(\bR\n" +
	"hasEmzones\x12$\n" +
	"\x0ehas_skill_zone\x18\x05 \x01(\bR\fhasSkillZone\"\xf6\x02\n" +
	"\aOptions\x12\x12\n" +
	"\x04seed\x18\x01 \x03(\x04R\x04seed\x12I\n" +
	"\x0eduelists_first\x18\x02 \x03(\v2\".YGOpen.Proto.Duel.Options.DuelistR\rduelistsFirst\x12K\n" +
	"\x0fduelists_second\x18\x03 \x03(\v2\".YGOpen.Proto.Duel.Options.DuelistR\x0eduelistsSecond\x123\n" +
	"\x05shape\x18\x04 \x01(\v2\x1d.YGOpen.Proto.Duel.FieldShapeR\x05shape\x1a\x89\x01\n" +
	"\aDuelist\x12\x1f\n" +
	"\vstarting_lp\x18\x01 \x01(\rR\n" +
	"startingLp\x12.\n" +
	"\x13starting_draw_count\x18\x02 \x01(\rR\x11startingDrawCount\x12-\n" +
	"\x13draw_count_per_turn\x18\x03 \x01(\rR\x10drawCountPerTurn\"\xa3\x01\n" +
	"\x05Chain\x127\n" +
	"\n" +
	"card_place\x18\x01 \x01(\v2\x18.YGOpen.Proto.Duel.PlaceR\tcardPlace\x12.\n" +
	"\x05place\x18\x02 \x01(\v2\x18.YGOpen.Proto.Duel.PlaceR\x05place\x121\n" +
	"\x06effect\x18\x03 \x01(\v2\x19.YGOpen.Proto.Duel.EffectR\x06effect\"3\n" +
	"\aCounter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"2\n" +
	"\x06Effect\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"Q\n" +
	"\x05Place\x12\x10\n" +
	"\x03con\x18\x01 \x01(\x05R\x03con\x12\x10\n" +
	"\x03loc\x18\x02 \x01(\rR\x03loc\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\rR\x03seq\x12\x12\n" +
	"\x04oseq\x18\x04 \x01(\x11R\x04oseq*\x98\x01\n" +
	"\vChainStatus\x12\x19\n" +
	"\x15CHAIN_STATUS_CHAINING\x10\x00\x12\x18\n" +
	"\x14CHAIN_STATUS_CHAINED\x10\x01\x12\x18\n" +
	"\x14CHAIN_STATUS_SOLVING\x10\x02\x12\x1c\n" +
	"\x18CHAIN_STATUS_ACT_NEGATED\x10\x03\x12\x1c\n" +
	"\x18CHAIN_STATUS_EFF_NEGATED\x10\x04B\x03\xf8\x01\x01b\x06proto3"

var (
	file_duel_data_proto_rawDescOnce sync.Once
	file_duel_data_proto_rawDescData []byte
)

func file_duel_data_proto_rawDescGZIP() []byte {
	file_duel_data_proto_rawDescOnce.Do(func() {
		file_duel_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_duel_data_proto_rawDesc), len(file_duel_data_proto_rawDesc)))
	})
	return file_duel_data_proto_rawDescData
}

var file_duel_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_duel_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_duel_data_proto_goTypes = []any{
	(ChainStatus)(0),        // 0: YGOpen.Proto.Duel.ChainStatus
	(*FieldShape)(nil),      // 1: YGOpen.Proto.Duel.FieldShape
	(*Options)(nil),         // 2: YGOpen.Proto.Duel.Options
	(*Chain)(nil),           // 3: YGOpen.Proto.Duel.Chain
	(*Counter)(nil),         // 4: YGOpen.Proto.Duel.Counter
	(*Effect)(nil),          // 5: YGOpen.Proto.Duel.Effect
	(*Place)(nil),           // 6: YGOpen.Proto.Duel.Place
	(*Options_Duelist)(nil), // 7: YGOpen.Proto.Duel.Options.Duelist
}
var file_duel_data_proto_depIdxs = []int32{
	7, // 0: YGOpen.Proto.Duel.Options.duelists_first:type_name -> YGOpen.Proto.Duel.Options.Duelist
	7, // 1: YGOpen.Proto.Duel.Options.duelists_second:type_name -> YGOpen.Proto.Duel.Options.Duelist
	1, // 2: YGOpen.Proto.Duel.Options.shape:type_name -> YGOpen.Proto.Duel.FieldShape
	6, // 3: YGOpen.Proto.Duel.Chain.card_place:type_name -> YGOpen.Proto.Duel.Place
	6, // 4: YGOpen.Proto.Duel.Chain.place:type_name -> YGOpen.Proto.Duel.Place
	5, // 5: YGOpen.Proto.Duel.Chain.effect:type_name -> YGOpen.Proto.Duel.Effect
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_duel_data_proto_init() }
func file_duel_data_proto_init() {
	if File_duel_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_duel_data_proto_rawDesc), len(file_duel_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_duel_data_proto_goTypes,
		DependencyIndexes: file_duel_data_proto_depIdxs,
		EnumInfos:         file_duel_data_proto_enumTypes,
		MessageInfos:      file_duel_data_proto_msgTypes,
	}.Build()
	File_duel_data_proto = out.File
	file_duel_data_proto_goTypes = nil
	file_duel_data_proto_depIdxs = nil
}
