//
// Copyright (c) 2022, Dylam De La Torre <dyxel04@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: duel_answer.proto

// TODO: Documentation.

package ygopenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Answer_SelectIdle_Action int32

const (
	Answer_SelectIdle_ACTION_ACTIVATE   Answer_SelectIdle_Action = 0
	Answer_SelectIdle_ACTION_SUMMON     Answer_SelectIdle_Action = 1
	Answer_SelectIdle_ACTION_SPSUMMON   Answer_SelectIdle_Action = 2
	Answer_SelectIdle_ACTION_REPOSITION Answer_SelectIdle_Action = 3
	Answer_SelectIdle_ACTION_MSET       Answer_SelectIdle_Action = 4
	Answer_SelectIdle_ACTION_SSET       Answer_SelectIdle_Action = 5
	Answer_SelectIdle_ACTION_ATTACK     Answer_SelectIdle_Action = 6
	Answer_SelectIdle_ACTION_SHUFFLE    Answer_SelectIdle_Action = 7
	Answer_SelectIdle_ACTION_PHASE      Answer_SelectIdle_Action = 8
)

// Enum value maps for Answer_SelectIdle_Action.
var (
	Answer_SelectIdle_Action_name = map[int32]string{
		0: "ACTION_ACTIVATE",
		1: "ACTION_SUMMON",
		2: "ACTION_SPSUMMON",
		3: "ACTION_REPOSITION",
		4: "ACTION_MSET",
		5: "ACTION_SSET",
		6: "ACTION_ATTACK",
		7: "ACTION_SHUFFLE",
		8: "ACTION_PHASE",
	}
	Answer_SelectIdle_Action_value = map[string]int32{
		"ACTION_ACTIVATE":   0,
		"ACTION_SUMMON":     1,
		"ACTION_SPSUMMON":   2,
		"ACTION_REPOSITION": 3,
		"ACTION_MSET":       4,
		"ACTION_SSET":       5,
		"ACTION_ATTACK":     6,
		"ACTION_SHUFFLE":    7,
		"ACTION_PHASE":      8,
	}
)

func (x Answer_SelectIdle_Action) Enum() *Answer_SelectIdle_Action {
	p := new(Answer_SelectIdle_Action)
	*p = x
	return p
}

func (x Answer_SelectIdle_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Answer_SelectIdle_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_duel_answer_proto_enumTypes[0].Descriptor()
}

func (Answer_SelectIdle_Action) Type() protoreflect.EnumType {
	return &file_duel_answer_proto_enumTypes[0]
}

func (x Answer_SelectIdle_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Answer_SelectIdle_Action.Descriptor instead.
func (Answer_SelectIdle_Action) EnumDescriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 3, 0}
}

type Answer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to T:
	//
	//	*Answer_SelectAttribute
	//	*Answer_SelectCard_
	//	*Answer_SelectCardCode
	//	*Answer_SelectCounter_
	//	*Answer_SelectEffect
	//	*Answer_SelectIdle_
	//	*Answer_SelectNumber
	//	*Answer_SelectPosition
	//	*Answer_SelectRace
	//	*Answer_SelectRockPaperScissors
	//	*Answer_SelectToChain_
	//	*Answer_SelectYesNo
	//	*Answer_SelectZone_
	//	*Answer_Sort_
	T             isAnswer_T `protobuf_oneof:"t"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_duel_answer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetT() isAnswer_T {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Answer) GetSelectAttribute() uint32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectAttribute); ok {
			return x.SelectAttribute
		}
	}
	return 0
}

func (x *Answer) GetSelectCard() *Answer_SelectCard {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectCard_); ok {
			return x.SelectCard
		}
	}
	return nil
}

func (x *Answer) GetSelectCardCode() uint32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectCardCode); ok {
			return x.SelectCardCode
		}
	}
	return 0
}

func (x *Answer) GetSelectCounter() *Answer_SelectCounter {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectCounter_); ok {
			return x.SelectCounter
		}
	}
	return nil
}

func (x *Answer) GetSelectEffect() uint32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectEffect); ok {
			return x.SelectEffect
		}
	}
	return 0
}

func (x *Answer) GetSelectIdle() *Answer_SelectIdle {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectIdle_); ok {
			return x.SelectIdle
		}
	}
	return nil
}

func (x *Answer) GetSelectNumber() uint32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectNumber); ok {
			return x.SelectNumber
		}
	}
	return 0
}

func (x *Answer) GetSelectPosition() uint32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectPosition); ok {
			return x.SelectPosition
		}
	}
	return 0
}

func (x *Answer) GetSelectRace() uint64 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectRace); ok {
			return x.SelectRace
		}
	}
	return 0
}

func (x *Answer) GetSelectRockPaperScissors() int32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectRockPaperScissors); ok {
			return x.SelectRockPaperScissors
		}
	}
	return 0
}

func (x *Answer) GetSelectToChain() *Answer_SelectToChain {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectToChain_); ok {
			return x.SelectToChain
		}
	}
	return nil
}

func (x *Answer) GetSelectYesNo() bool {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectYesNo); ok {
			return x.SelectYesNo
		}
	}
	return false
}

func (x *Answer) GetSelectZone() *Answer_SelectZone {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectZone_); ok {
			return x.SelectZone
		}
	}
	return nil
}

func (x *Answer) GetSort() *Answer_Sort {
	if x != nil {
		if x, ok := x.T.(*Answer_Sort_); ok {
			return x.Sort
		}
	}
	return nil
}

type isAnswer_T interface {
	isAnswer_T()
}

type Answer_SelectAttribute struct {
	// Selected attribute or attributes OR'd together.
	SelectAttribute uint32 `protobuf:"varint,1,opt,name=select_attribute,json=selectAttribute,proto3,oneof"`
}

type Answer_SelectCard_ struct {
	// Cancel selection, indexes of cards and counter counts (if any).
	SelectCard *Answer_SelectCard `protobuf:"bytes,2,opt,name=select_card,json=selectCard,proto3,oneof"`
}

type Answer_SelectCardCode struct {
	// Selected card code.
	SelectCardCode uint32 `protobuf:"varint,3,opt,name=select_card_code,json=selectCardCode,proto3,oneof"`
}

type Answer_SelectCounter_ struct {
	// TODO
	SelectCounter *Answer_SelectCounter `protobuf:"bytes,4,opt,name=select_counter,json=selectCounter,proto3,oneof"`
}

type Answer_SelectEffect struct {
	// Index of selected option/effect.
	SelectEffect uint32 `protobuf:"varint,5,opt,name=select_effect,json=selectEffect,proto3,oneof"`
}

type Answer_SelectIdle_ struct {
	// Shuffle action, value of phase or "actioned" card.
	SelectIdle *Answer_SelectIdle `protobuf:"bytes,6,opt,name=select_idle,json=selectIdle,proto3,oneof"`
}

type Answer_SelectNumber struct {
	// Index of selected number.
	SelectNumber uint32 `protobuf:"varint,7,opt,name=select_number,json=selectNumber,proto3,oneof"`
}

type Answer_SelectPosition struct {
	// Selected position or positions OR'd together.
	SelectPosition uint32 `protobuf:"varint,8,opt,name=select_position,json=selectPosition,proto3,oneof"`
}

type Answer_SelectRace struct {
	// Selected race or races OR'd together.
	SelectRace uint64 `protobuf:"varint,9,opt,name=select_race,json=selectRace,proto3,oneof"`
}

type Answer_SelectRockPaperScissors struct {
	// Self-explanatory.
	SelectRockPaperScissors int32 `protobuf:"varint,10,opt,name=select_rock_paper_scissors,json=selectRockPaperScissors,proto3,oneof"`
}

type Answer_SelectToChain_ struct {
	// No operation (Do not chain anything), or index of card to chain.
	SelectToChain *Answer_SelectToChain `protobuf:"bytes,11,opt,name=select_to_chain,json=selectToChain,proto3,oneof"`
}

type Answer_SelectYesNo struct {
	// Self-explanatory.
	SelectYesNo bool `protobuf:"varint,12,opt,name=select_yes_no,json=selectYesNo,proto3,oneof"`
}

type Answer_SelectZone_ struct {
	// Zone or zones to select.
	SelectZone *Answer_SelectZone `protobuf:"bytes,13,opt,name=select_zone,json=selectZone,proto3,oneof"`
}

type Answer_Sort_ struct {
	// Indexes of cards sorted by client, skippable.
	Sort *Answer_Sort `protobuf:"bytes,14,opt,name=sort,proto3,oneof"`
}

func (*Answer_SelectAttribute) isAnswer_T() {}

func (*Answer_SelectCard_) isAnswer_T() {}

func (*Answer_SelectCardCode) isAnswer_T() {}

func (*Answer_SelectCounter_) isAnswer_T() {}

func (*Answer_SelectEffect) isAnswer_T() {}

func (*Answer_SelectIdle_) isAnswer_T() {}

func (*Answer_SelectNumber) isAnswer_T() {}

func (*Answer_SelectPosition) isAnswer_T() {}

func (*Answer_SelectRace) isAnswer_T() {}

func (*Answer_SelectRockPaperScissors) isAnswer_T() {}

func (*Answer_SelectToChain_) isAnswer_T() {}

func (*Answer_SelectYesNo) isAnswer_T() {}

func (*Answer_SelectZone_) isAnswer_T() {}

func (*Answer_Sort_) isAnswer_T() {}

type Answer_Indexes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Corresponds to the indexes the request message had for its
	// repeated fields.
	Values        []uint32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_Indexes) Reset() {
	*x = Answer_Indexes{}
	mi := &file_duel_answer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_Indexes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_Indexes) ProtoMessage() {}

func (x *Answer_Indexes) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_Indexes.ProtoReflect.Descriptor instead.
func (*Answer_Indexes) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Answer_Indexes) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Answer_SelectCard struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to T:
	//
	//	*Answer_SelectCard_Cancel
	//	*Answer_SelectCard_Finish
	//	*Answer_SelectCard_Indexes
	T             isAnswer_SelectCard_T `protobuf_oneof:"t"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_SelectCard) Reset() {
	*x = Answer_SelectCard{}
	mi := &file_duel_answer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_SelectCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_SelectCard) ProtoMessage() {}

func (x *Answer_SelectCard) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_SelectCard.ProtoReflect.Descriptor instead.
func (*Answer_SelectCard) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Answer_SelectCard) GetT() isAnswer_SelectCard_T {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Answer_SelectCard) GetCancel() bool {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectCard_Cancel); ok {
			return x.Cancel
		}
	}
	return false
}

func (x *Answer_SelectCard) GetFinish() bool {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectCard_Finish); ok {
			return x.Finish
		}
	}
	return false
}

func (x *Answer_SelectCard) GetIndexes() *Answer_Indexes {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectCard_Indexes); ok {
			return x.Indexes
		}
	}
	return nil
}

type isAnswer_SelectCard_T interface {
	isAnswer_SelectCard_T()
}

type Answer_SelectCard_Cancel struct {
	// Cancel the selection. Only if it can be canceled.
	Cancel bool `protobuf:"varint,1,opt,name=cancel,proto3,oneof"`
}

type Answer_SelectCard_Finish struct {
	// Finish the selection as it is, if possible.
	Finish bool `protobuf:"varint,2,opt,name=finish,proto3,oneof"`
}

type Answer_SelectCard_Indexes struct {
	// List of selected cards.
	Indexes *Answer_Indexes `protobuf:"bytes,3,opt,name=indexes,proto3,oneof"`
}

func (*Answer_SelectCard_Cancel) isAnswer_SelectCard_T() {}

func (*Answer_SelectCard_Finish) isAnswer_SelectCard_T() {}

func (*Answer_SelectCard_Indexes) isAnswer_SelectCard_T() {}

type Answer_SelectCounter struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Values        []*Answer_SelectCounter_XPair `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_SelectCounter) Reset() {
	*x = Answer_SelectCounter{}
	mi := &file_duel_answer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_SelectCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_SelectCounter) ProtoMessage() {}

func (x *Answer_SelectCounter) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_SelectCounter.ProtoReflect.Descriptor instead.
func (*Answer_SelectCounter) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Answer_SelectCounter) GetValues() []*Answer_SelectCounter_XPair {
	if x != nil {
		return x.Values
	}
	return nil
}

type Answer_SelectIdle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to T:
	//
	//	*Answer_SelectIdle_Shuffle
	//	*Answer_SelectIdle_Phase
	//	*Answer_SelectIdle_CardAction_
	T             isAnswer_SelectIdle_T `protobuf_oneof:"t"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_SelectIdle) Reset() {
	*x = Answer_SelectIdle{}
	mi := &file_duel_answer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_SelectIdle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_SelectIdle) ProtoMessage() {}

func (x *Answer_SelectIdle) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_SelectIdle.ProtoReflect.Descriptor instead.
func (*Answer_SelectIdle) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Answer_SelectIdle) GetT() isAnswer_SelectIdle_T {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Answer_SelectIdle) GetShuffle() bool {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectIdle_Shuffle); ok {
			return x.Shuffle
		}
	}
	return false
}

func (x *Answer_SelectIdle) GetPhase() uint32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectIdle_Phase); ok {
			return x.Phase
		}
	}
	return 0
}

func (x *Answer_SelectIdle) GetCardAction() *Answer_SelectIdle_CardAction {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectIdle_CardAction_); ok {
			return x.CardAction
		}
	}
	return nil
}

type isAnswer_SelectIdle_T interface {
	isAnswer_SelectIdle_T()
}

type Answer_SelectIdle_Shuffle struct {
	// Perform hand shuffling.
	Shuffle bool `protobuf:"varint,1,opt,name=shuffle,proto3,oneof"`
}

type Answer_SelectIdle_Phase struct {
	// Attempt to go to the selected phase.
	Phase uint32 `protobuf:"varint,2,opt,name=phase,proto3,oneof"`
}

type Answer_SelectIdle_CardAction_ struct {
	// Perform an action on a card.
	CardAction *Answer_SelectIdle_CardAction `protobuf:"bytes,3,opt,name=card_action,json=cardAction,proto3,oneof"`
}

func (*Answer_SelectIdle_Shuffle) isAnswer_SelectIdle_T() {}

func (*Answer_SelectIdle_Phase) isAnswer_SelectIdle_T() {}

func (*Answer_SelectIdle_CardAction_) isAnswer_SelectIdle_T() {}

type Answer_SelectToChain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to T:
	//
	//	*Answer_SelectToChain_NoOp
	//	*Answer_SelectToChain_Index
	T             isAnswer_SelectToChain_T `protobuf_oneof:"t"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_SelectToChain) Reset() {
	*x = Answer_SelectToChain{}
	mi := &file_duel_answer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_SelectToChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_SelectToChain) ProtoMessage() {}

func (x *Answer_SelectToChain) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_SelectToChain.ProtoReflect.Descriptor instead.
func (*Answer_SelectToChain) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Answer_SelectToChain) GetT() isAnswer_SelectToChain_T {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Answer_SelectToChain) GetNoOp() bool {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectToChain_NoOp); ok {
			return x.NoOp
		}
	}
	return false
}

func (x *Answer_SelectToChain) GetIndex() uint32 {
	if x != nil {
		if x, ok := x.T.(*Answer_SelectToChain_Index); ok {
			return x.Index
		}
	}
	return 0
}

type isAnswer_SelectToChain_T interface {
	isAnswer_SelectToChain_T()
}

type Answer_SelectToChain_NoOp struct {
	// Don't chain anything. Invalid if forced is true.
	NoOp bool `protobuf:"varint,1,opt,name=no_op,json=noOp,proto3,oneof"`
}

type Answer_SelectToChain_Index struct {
	// Corresponds to the index the request message had for its repeated
	// field.
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3,oneof"`
}

func (*Answer_SelectToChain_NoOp) isAnswer_SelectToChain_T() {}

func (*Answer_SelectToChain_Index) isAnswer_SelectToChain_T() {}

type Answer_SelectZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Places        []*Place               `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_SelectZone) Reset() {
	*x = Answer_SelectZone{}
	mi := &file_duel_answer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_SelectZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_SelectZone) ProtoMessage() {}

func (x *Answer_SelectZone) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_SelectZone.ProtoReflect.Descriptor instead.
func (*Answer_SelectZone) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Answer_SelectZone) GetPlaces() []*Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type Answer_Sort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to T:
	//
	//	*Answer_Sort_Skip
	//	*Answer_Sort_Indexes
	T             isAnswer_Sort_T `protobuf_oneof:"t"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_Sort) Reset() {
	*x = Answer_Sort{}
	mi := &file_duel_answer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_Sort) ProtoMessage() {}

func (x *Answer_Sort) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_Sort.ProtoReflect.Descriptor instead.
func (*Answer_Sort) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Answer_Sort) GetT() isAnswer_Sort_T {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Answer_Sort) GetSkip() bool {
	if x != nil {
		if x, ok := x.T.(*Answer_Sort_Skip); ok {
			return x.Skip
		}
	}
	return false
}

func (x *Answer_Sort) GetIndexes() *Answer_Indexes {
	if x != nil {
		if x, ok := x.T.(*Answer_Sort_Indexes); ok {
			return x.Indexes
		}
	}
	return nil
}

type isAnswer_Sort_T interface {
	isAnswer_Sort_T()
}

type Answer_Sort_Skip struct {
	// Skip sorting, let the core decide the order.
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3,oneof"`
}

type Answer_Sort_Indexes struct {
	// List of sorted cards.
	Indexes *Answer_Indexes `protobuf:"bytes,2,opt,name=indexes,proto3,oneof"`
}

func (*Answer_Sort_Skip) isAnswer_Sort_T() {}

func (*Answer_Sort_Indexes) isAnswer_Sort_T() {}

type Answer_SelectCounter_XPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Corresponds to the indexes the request message had for its
	// repeated fields.
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Number of counters to select from that particular card index
	// without exceeding the amount given in the request message.
	Amount        uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_SelectCounter_XPair) Reset() {
	*x = Answer_SelectCounter_XPair{}
	mi := &file_duel_answer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_SelectCounter_XPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_SelectCounter_XPair) ProtoMessage() {}

func (x *Answer_SelectCounter_XPair) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_SelectCounter_XPair.ProtoReflect.Descriptor instead.
func (*Answer_SelectCounter_XPair) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Answer_SelectCounter_XPair) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Answer_SelectCounter_XPair) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Answer_SelectIdle_CardAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any of the previously defined actions except shuffle or phase.
	Action Answer_SelectIdle_Action `protobuf:"varint,1,opt,name=action,proto3,enum=YGOpen.Proto.Duel.Answer_SelectIdle_Action" json:"action,omitempty"`
	// Corresponds to the index the chosen card had on its respective
	// repeated field in the SelectIdle request message.
	Index         uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_SelectIdle_CardAction) Reset() {
	*x = Answer_SelectIdle_CardAction{}
	mi := &file_duel_answer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_SelectIdle_CardAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_SelectIdle_CardAction) ProtoMessage() {}

func (x *Answer_SelectIdle_CardAction) ProtoReflect() protoreflect.Message {
	mi := &file_duel_answer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_SelectIdle_CardAction.ProtoReflect.Descriptor instead.
func (*Answer_SelectIdle_CardAction) Descriptor() ([]byte, []int) {
	return file_duel_answer_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Answer_SelectIdle_CardAction) GetAction() Answer_SelectIdle_Action {
	if x != nil {
		return x.Action
	}
	return Answer_SelectIdle_ACTION_ACTIVATE
}

func (x *Answer_SelectIdle_CardAction) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_duel_answer_proto protoreflect.FileDescriptor

const file_duel_answer_proto_rawDesc = "" +
	"\n" +
	"\x11duel_answer.proto\x12\x11YGOpen.Proto.Duel\x1a\x0fduel_data.proto\"\xfd\r\n" +
	"\x06Answer\x12+\n" +
	"\x10select_attribute\x18\x01 \x01(\rH\x00R\x0fselectAttribute\x12G\n" +
	"\vselect_card\x18\x02 \x01(\v2$.YGOpen.Proto.Duel.Answer.SelectCardH\x00R\n" +
	"selectCard\x12*\n" +
	"\x10select_card_code\x18\x03 \x01(\rH\x00R\x0eselectCardCode\x12P\n" +
	"\x0eselect_counter\x18\x04 \x01(\v2'.YGOpen.Proto.Duel.Answer.SelectCounterH\x00R\rselectCounter\x12%\n" +
	"\rselect_effect\x18\x05 \x01(\rH\x00R\fselectEffect\x12G\n" +
	"\vselect_idle\x18\x06 \x01(\v2$.YGOpen.Proto.Duel.Answer.SelectIdleH\x00R\n" +
	"selectIdle\x12%\n" +
	"\rselect_number\x18\a \x01(\rH\x00R\fselectNumber\x12)\n" +
	"\x0fselect_position\x18\b \x01(\rH\x00R\x0eselectPosition\x12!\n" +
	"\vselect_race\x18\t \x01(\x04H\x00R\n" +
	"selectRace\x12=\n" +
	"\x1aselect_rock_paper_scissors\x18\n" +
	" \x01(\x05H\x00R\x17selectRockPaperScissors\x12Q\n" +
	"\x0fselect_to_chain\x18\v \x01(\v2'.YGOpen.Proto.Duel.Answer.SelectToChainH\x00R\rselectToChain\x12$\n" +
	"\rselect_yes_no\x18\f \x01(\bH\x00R\vselectYesNo\x12G\n" +
	"\vselect_zone\x18\r \x01(\v2$.YGOpen.Proto.Duel.Answer.SelectZoneH\x00R\n" +
	"selectZone\x124\n" +
	"\x04sort\x18\x0e \x01(\v2\x1e.YGOpen.Proto.Duel.Answer.SortH\x00R\x04sort\x1a!\n" +
	"\aIndexes\x12\x16\n" +
	"\x06values\x18\x01 \x03(\rR\x06values\x1a\x84\x01\n" +
	"\n" +
	"SelectCard\x12\x18\n" +
	"\x06cancel\x18\x01 \x01(\bH\x00R\x06cancel\x12\x18\n" +
	"\x06finish\x18\x02 \x01(\bH\x00R\x06finish\x12=\n" +
	"\aindexes\x18\x03 \x01(\v2!.YGOpen.Proto.Duel.Answer.IndexesH\x00R\aindexesB\x03\n" +
	"\x01t\x1a\x8d\x01\n" +
	"\rSelectCounter\x12E\n" +
	"\x06values\x18\x01 \x03(\v2-.YGOpen.Proto.Duel.Answer.SelectCounter._PairR\x06values\x1a5\n" +
	"\x05_Pair\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x1a\xbc\x03\n" +
	"\n" +
	"SelectIdle\x12\x1a\n" +
	"\ashuffle\x18\x01 \x01(\bH\x00R\ashuffle\x12\x16\n" +
	"\x05phase\x18\x02 \x01(\rH\x00R\x05phase\x12R\n" +
	"\vcard_action\x18\x03 \x01(\v2/.YGOpen.Proto.Duel.Answer.SelectIdle.CardActionH\x00R\n" +
	"cardAction\x1ag\n" +
	"\n" +
	"CardAction\x12C\n" +
	"\x06action\x18\x01 \x01(\x0e2+.YGOpen.Proto.Duel.Answer.SelectIdle.ActionR\x06action\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\xb7\x01\n" +
	"\x06Action\x12\x13\n" +
	"\x0fACTION_ACTIVATE\x10\x00\x12\x11\n" +
	"\rACTION_SUMMON\x10\x01\x12\x13\n" +
	"\x0fACTION_SPSUMMON\x10\x02\x12\x15\n" +
	"\x11ACTION_REPOSITION\x10\x03\x12\x0f\n" +
	"\vACTION_MSET\x10\x04\x12\x0f\n" +
	"\vACTION_SSET\x10\x05\x12\x11\n" +
	"\rACTION_ATTACK\x10\x06\x12\x12\n" +
	"\x0eACTION_SHUFFLE\x10\a\x12\x10\n" +
	"\fACTION_PHASE\x10\bB\x03\n" +
	"\x01t\x1aC\n" +
	"\rSelectToChain\x12\x15\n" +
	"\x05no_op\x18\x01 \x01(\bH\x00R\x04noOp\x12\x16\n" +
	"\x05index\x18\x02 \x01(\rH\x00R\x05indexB\x03\n" +
	"\x01t\x1a>\n" +
	"\n" +
	"SelectZone\x120\n" +
	"\x06places\x18\x01 \x03(\v2\x18.YGOpen.Proto.Duel.PlaceR\x06places\x1a`\n" +
	"\x04Sort\x12\x14\n" +
	"\x04skip\x18\x01 \x01(\bH\x00R\x04skip\x12=\n" +
	"\aindexes\x18\x02 \x01(\v2!.YGOpen.Proto.Duel.Answer.IndexesH\x00R\aindexesB\x03\n" +
	"\x01tB\x03\n" +
	"\x01tB\x03\xf8\x01\x01b\x06proto3"

var (
	file_duel_answer_proto_rawDescOnce sync.Once
	file_duel_answer_proto_rawDescData []byte
)

func file_duel_answer_proto_rawDescGZIP() []byte {
	file_duel_answer_proto_rawDescOnce.Do(func() {
		file_duel_answer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_duel_answer_proto_rawDesc), len(file_duel_answer_proto_rawDesc)))
	})
	return file_duel_answer_proto_rawDescData
}

var file_duel_answer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_duel_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_duel_answer_proto_goTypes = []any{
	(Answer_SelectIdle_Action)(0),        // 0: YGOpen.Proto.Duel.Answer.SelectIdle.Action
	(*Answer)(nil),                       // 1: YGOpen.Proto.Duel.Answer
	(*Answer_Indexes)(nil),               // 2: YGOpen.Proto.Duel.Answer.Indexes
	(*Answer_SelectCard)(nil),            // 3: YGOpen.Proto.Duel.Answer.SelectCard
	(*Answer_SelectCounter)(nil),         // 4: YGOpen.Proto.Duel.Answer.SelectCounter
	(*Answer_SelectIdle)(nil),            // 5: YGOpen.Proto.Duel.Answer.SelectIdle
	(*Answer_SelectToChain)(nil),         // 6: YGOpen.Proto.Duel.Answer.SelectToChain
	(*Answer_SelectZone)(nil),            // 7: YGOpen.Proto.Duel.Answer.SelectZone
	(*Answer_Sort)(nil),                  // 8: YGOpen.Proto.Duel.Answer.Sort
	(*Answer_SelectCounter_XPair)(nil),   // 9: YGOpen.Proto.Duel.Answer.SelectCounter._Pair
	(*Answer_SelectIdle_CardAction)(nil), // 10: YGOpen.Proto.Duel.Answer.SelectIdle.CardAction
	(*Place)(nil),                        // 11: YGOpen.Proto.Duel.Place
}
var file_duel_answer_proto_depIdxs = []int32{
	3,  // 0: YGOpen.Proto.Duel.Answer.select_card:type_name -> YGOpen.Proto.Duel.Answer.SelectCard
	4,  // 1: YGOpen.Proto.Duel.Answer.select_counter:type_name -> YGOpen.Proto.Duel.Answer.SelectCounter
	5,  // 2: YGOpen.Proto.Duel.Answer.select_idle:type_name -> YGOpen.Proto.Duel.Answer.SelectIdle
	6,  // 3: YGOpen.Proto.Duel.Answer.select_to_chain:type_name -> YGOpen.Proto.Duel.Answer.SelectToChain
	7,  // 4: YGOpen.Proto.Duel.Answer.select_zone:type_name -> YGOpen.Proto.Duel.Answer.SelectZone
	8,  // 5: YGOpen.Proto.Duel.Answer.sort:type_name -> YGOpen.Proto.Duel.Answer.Sort
	2,  // 6: YGOpen.Proto.Duel.Answer.SelectCard.indexes:type_name -> YGOpen.Proto.Duel.Answer.Indexes
	9,  // 7: YGOpen.Proto.Duel.Answer.SelectCounter.values:type_name -> YGOpen.Proto.Duel.Answer.SelectCounter._Pair
	10, // 8: YGOpen.Proto.Duel.Answer.SelectIdle.card_action:type_name -> YGOpen.Proto.Duel.Answer.SelectIdle.CardAction
	11, // 9: YGOpen.Proto.Duel.Answer.SelectZone.places:type_name -> YGOpen.Proto.Duel.Place
	2,  // 10: YGOpen.Proto.Duel.Answer.Sort.indexes:type_name -> YGOpen.Proto.Duel.Answer.Indexes
	0,  // 11: YGOpen.Proto.Duel.Answer.SelectIdle.CardAction.action:type_name -> YGOpen.Proto.Duel.Answer.SelectIdle.Action
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_duel_answer_proto_init() }
func file_duel_answer_proto_init() {
	if File_duel_answer_proto != nil {
		return
	}
	file_duel_data_proto_init()
	file_duel_answer_proto_msgTypes[0].OneofWrappers = []any{
		(*Answer_SelectAttribute)(nil),
		(*Answer_SelectCard_)(nil),
		(*Answer_SelectCardCode)(nil),
		(*Answer_SelectCounter_)(nil),
		(*Answer_SelectEffect)(nil),
		(*Answer_SelectIdle_)(nil),
		(*Answer_SelectNumber)(nil),
		(*Answer_SelectPosition)(nil),
		(*Answer_SelectRace)(nil),
		(*Answer_SelectRockPaperScissors)(nil),
		(*Answer_SelectToChain_)(nil),
		(*Answer_SelectYesNo)(nil),
		(*Answer_SelectZone_)(nil),
		(*Answer_Sort_)(nil),
	}
	file_duel_answer_proto_msgTypes[2].OneofWrappers = []any{
		(*Answer_SelectCard_Cancel)(nil),
		(*Answer_SelectCard_Finish)(nil),
		(*Answer_SelectCard_Indexes)(nil),
	}
	file_duel_answer_proto_msgTypes[4].OneofWrappers = []any{
		(*Answer_SelectIdle_Shuffle)(nil),
		(*Answer_SelectIdle_Phase)(nil),
		(*Answer_SelectIdle_CardAction_)(nil),
	}
	file_duel_answer_proto_msgTypes[5].OneofWrappers = []any{
		(*Answer_SelectToChain_NoOp)(nil),
		(*Answer_SelectToChain_Index)(nil),
	}
	file_duel_answer_proto_msgTypes[7].OneofWrappers = []any{
		(*Answer_Sort_Skip)(nil),
		(*Answer_Sort_Indexes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_duel_answer_proto_rawDesc), len(file_duel_answer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_duel_answer_proto_goTypes,
		DependencyIndexes: file_duel_answer_proto_depIdxs,
		EnumInfos:         file_duel_answer_proto_enumTypes,
		MessageInfos:      file_duel_answer_proto_msgTypes,
	}.Build()
	File_duel_answer_proto = out.File
	file_duel_answer_proto_goTypes = nil
	file_duel_answer_proto_depIdxs = nil
}
